### ISSUE TITLE
Deck from workshop at re:Invent?

### ISSUE THREAD

**Issue by slalom-kimadams** [mike-calder/AIM368-Instructions#1]
Could you please share the deck from the workshop at re:Invent last week?

**Comment by mike-calder** [comment]
The slide decks for all re:Invent workshops should be available within a week or so on this page: https://aws.amazon.com/events/events-content

**Comment by mike-calder** [comment]
I'll keep this issue open until it's been published.

**Comment by mike-calder** [comment]
Looks like the slide deck has been uploaded! You can search for it on the page I linked to earlier, but here's the direct link: https://d1.awsstatic.com/events/reinvent/2019/Experience_the_real-world_ML_lifecycle_with_Amazon_SageMaker_AIM368.pdf
